CREATE DATABASE [BI_DW]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'BI_DW', FILENAME = N'D:\BIDatabases\BI_DW.mdf' , SIZE = 5120KB , FILEGROWTH = 524288KB )
 LOG ON 
( NAME = N'BI_DW_log', FILENAME = N'D:\BIDatabases\BI_DW_log.ldf' , SIZE = 1024KB , FILEGROWTH = 524288KB )
GO
ALTER DATABASE [BI_DW] SET COMPATIBILITY_LEVEL = 110
GO
ALTER DATABASE [BI_DW] SET ANSI_NULL_DEFAULT OFF 
GO
ALTER DATABASE [BI_DW] SET ANSI_NULLS OFF 
GO
ALTER DATABASE [BI_DW] SET ANSI_PADDING OFF 
GO
ALTER DATABASE [BI_DW] SET ANSI_WARNINGS OFF 
GO
ALTER DATABASE [BI_DW] SET ARITHABORT OFF 
GO
ALTER DATABASE [BI_DW] SET AUTO_CLOSE OFF 
GO
ALTER DATABASE [BI_DW] SET AUTO_CREATE_STATISTICS ON 
GO
ALTER DATABASE [BI_DW] SET AUTO_SHRINK OFF 
GO
ALTER DATABASE [BI_DW] SET AUTO_UPDATE_STATISTICS ON 
GO
ALTER DATABASE [BI_DW] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO
ALTER DATABASE [BI_DW] SET CURSOR_DEFAULT  GLOBAL 
GO
ALTER DATABASE [BI_DW] SET CONCAT_NULL_YIELDS_NULL OFF 
GO
ALTER DATABASE [BI_DW] SET NUMERIC_ROUNDABORT OFF 
GO
ALTER DATABASE [BI_DW] SET QUOTED_IDENTIFIER OFF 
GO
ALTER DATABASE [BI_DW] SET RECURSIVE_TRIGGERS OFF 
GO
ALTER DATABASE [BI_DW] SET  DISABLE_BROKER 
GO
ALTER DATABASE [BI_DW] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO
ALTER DATABASE [BI_DW] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO
ALTER DATABASE [BI_DW] SET PARAMETERIZATION SIMPLE 
GO
ALTER DATABASE [BI_DW] SET READ_COMMITTED_SNAPSHOT OFF 
GO
ALTER DATABASE [BI_DW] SET  READ_WRITE 
GO
ALTER DATABASE [BI_DW] SET RECOVERY SIMPLE 
GO
ALTER DATABASE [BI_DW] SET  MULTI_USER 
GO
ALTER DATABASE [BI_DW] SET PAGE_VERIFY CHECKSUM  
GO
ALTER DATABASE [BI_DW] SET TARGET_RECOVERY_TIME = 0 SECONDS 
GO
USE [BI_DW]
GO
IF NOT EXISTS (SELECT name FROM sys.filegroups WHERE is_default=1 AND name = N'PRIMARY') ALTER DATABASE [BI_DW] MODIFY FILEGROUP [PRIMARY] DEFAULT
GO