USE [BI_DW]
GO

/*
索引文件
*/
IF (EXISTS(SELECT 1 FROM [sys].[sysfiles] AS sf WITH(NOLOCK) WHERE [sf].[name] = 'PF_PRIMARY_Index01'))
BEGIN
	DBCC SHRINKFILE([PF_PRIMARY_Index01], EMPTYFILE);
	ALTER DATABASE [BI_DW] REMOVE FILE [PF_PRIMARY_Index01];
END
GO
IF (EXISTS(SELECT 1 FROM [sys].[sysfiles] AS sf WITH(NOLOCK) WHERE [sf].[name] = 'PF_PRIMARY_Index02'))
BEGIN
	DBCC SHRINKFILE([PF_PRIMARY_Index02], EMPTYFILE);
	ALTER DATABASE [BI_DW] REMOVE FILE [PF_PRIMARY_Index02];
END
GO
IF (EXISTS(SELECT 1 FROM [sys].[sysfiles] AS sf WITH(NOLOCK) WHERE [sf].[name] = 'PF_PRIMARY_Index03'))
BEGIN
	DBCC SHRINKFILE([PF_PRIMARY_Index03], EMPTYFILE);
	ALTER DATABASE [BI_DW] REMOVE FILE [PF_PRIMARY_Index03];
END
GO
IF (EXISTS(SELECT 1 FROM [sys].[sysfiles] AS sf WITH(NOLOCK) WHERE [sf].[name] = 'PF_PRIMARY_Index04'))
BEGIN
	DBCC SHRINKFILE([PF_PRIMARY_Index04], EMPTYFILE);
	ALTER DATABASE [BI_DW] REMOVE FILE [PF_PRIMARY_Index04];
END
GO
IF (EXISTS(SELECT 1 FROM [sys].[sysfiles] AS sf WITH(NOLOCK) WHERE [sf].[name] = 'PF_PRIMARY_Index05'))
BEGIN
	DBCC SHRINKFILE([PF_PRIMARY_Index05], EMPTYFILE);
	ALTER DATABASE [BI_DW] REMOVE FILE [PF_PRIMARY_Index05];
END
GO
/*
索引文件组
*/
IF (EXISTS(SELECT 1 FROM [sys].[filegroups] AS fg WITH(NOLOCK) WHERE [fg].[name] = 'FG_PRIMARY_Index'))
BEGIN
	ALTER DATABASE [BI_DW] REMOVE FILEGROUP [FG_PRIMARY_Index]
END
GO


/*
索引文件组
*/
ALTER DATABASE [BI_DW] ADD FILEGROUP [FG_PRIMARY_Index]
GO


/*
创建索引文件
*/
ALTER DATABASE [BI_DW] ADD
FILE (
	NAME = 'PF_PRIMARY_Index01',
	FILENAME = 'D:\BIDatabases\PRIMARY_Indexs\PF_PRIMARY_Index01.NDF',
	SIZE = 2048MB,
	FILEGROWTH = 512MB
) TO FILEGROUP [FG_PRIMARY_Index];
GO

ALTER DATABASE [BI_DW] ADD
FILE (
	NAME = 'PF_PRIMARY_Index02',
	FILENAME = 'D:\BIDatabases\PRIMARY_Indexs\PF_PRIMARY_Index02.NDF',
	SIZE = 2048MB,
	FILEGROWTH = 512MB
) TO FILEGROUP [FG_PRIMARY_Index];
GO

ALTER DATABASE [BI_DW] ADD
FILE (
	NAME = 'PF_PRIMARY_Index03',
	FILENAME = 'D:\BIDatabases\PRIMARY_Indexs\PF_PRIMARY_Index03.NDF',
	SIZE = 2048MB,
	FILEGROWTH = 512MB
) TO FILEGROUP [FG_PRIMARY_Index];
GO

ALTER DATABASE [BI_DW] ADD
FILE (
	NAME = 'PF_PRIMARY_Index04',
	FILENAME = 'D:\BIDatabases\PRIMARY_Indexs\PF_PRIMARY_Index04.NDF',
	SIZE = 2048MB,
	FILEGROWTH = 512MB
) TO FILEGROUP [FG_PRIMARY_Index];
GO


ALTER DATABASE [BI_DW] ADD
FILE (
	NAME = 'PF_PRIMARY_Index05',
	FILENAME = 'D:\BIDatabases\PRIMARY_Indexs\PF_PRIMARY_Index05.NDF',
	SIZE = 2048MB,
	FILEGROWTH = 512MB
) TO FILEGROUP [FG_PRIMARY_Index];
GO