IF (OBJECT_ID(N'[dbo].[TBTest]', N'U') IS NOT NULL)
BEGIN
	DROP TABLE [dbo].[TBTest];
END
GO


CREATE TABLE [dbo].[TBTest](

    [id] [int] IDENTITY(1,1) NOT NULL,

    [Title] [nvarchar](50) NULL,

    [Amount] [decimal](18, 0) NULL,

CONSTRAINT [PK_TBTest] PRIMARY KEY CLUSTERED

(

    [id] ASC

)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]

) ON [PRIMARY]

TRUNCATE TABLE dbo.TBTest

SELECT 'A' AS [Title],10 AS [Amount]
UNION ALL
SELECT 'B',20
UNION ALL
SELECT 'C',30
UNION ALL
SELECT 'D',40
UNION ALL
SELECT 'E',50
--UPDATE dbo.TBTest SET id =3 WHERE Title='D'

SELECT * FROM dbo.TBTest