--销量类型
IF (OBJECT_ID(N'[Dim_SaleQtyType]', 'U') IS NOT NULL)
BEGIN
	DROP TABLE [Dim_SaleQtyType];
END
GO

CREATE TABLE [Dim_SaleQtyType]
(
	 [SaleQtyTypeId] INT NOT NULL
	,[SaleQtyTypeName] NVARCHAR(20) NOT NULL
	,[SaleTypeGroupMDX] NVARCHAR(255) NOT NULL
)
GO

IF (EXISTS(SELECT 1 FROM [sys].[indexes] AS ix WHERE [ix].[name] = 'CIX_Dim_SaleQtyType_01'))
BEGIN
	DROP INDEX [dbo].[Dim_SaleQtyType].[CIX_Dim_SaleQtyType_01]
END
GO

CREATE UNIQUE CLUSTERED INDEX [CIX_Dim_SaleQtyType_01] ON [dbo].[Dim_SaleQtyType]
(
	[SaleQtyTypeId] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, SORT_IN_TEMPDB = OFF, IGNORE_DUP_KEY = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [FG_PRIMARY_Index]
GO

ALTER TABLE [dbo].[Dim_SaleQtyType] ADD CONSTRAINT PK_Dim_SaleQtyType_Id PRIMARY KEY([SaleQtyTypeId])
GO


--统计方法
IF (OBJECT_ID(N'[dbo].[Dim_TJFF]', N'U') IS NOT NULL)
BEGIN
	DROP TABLE [dbo].[Dim_TJFF];
END
GO

CREATE TABLE [dbo].[Dim_TJFF]
(
	[TJFFId] INT NOT NULL
	,[TJFFName] NVARCHAR(50) NOT NULL
	,[TJFFGroupMDX] NVARCHAR(255) NOT NULL
)
GO

IF (EXISTS(SELECT 1 FROM [sys].[indexes] AS ix WITH(NOLOCK) WHERE [ix].[name] = 'CIX_Dim_TJFF_01'))
BEGIN
	DROP INDEX [dbo].[Dim_TJFF].[CIX_Dim_TJFF_01];
END
GO

CREATE UNIQUE CLUSTERED INDEX [CIX_Dim_TJFF_01] ON [dbo].[Dim_TJFF]
(
	[TJFFId] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, SORT_IN_TEMPDB = OFF, IGNORE_DUP_KEY = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [FG_PRIMARY_Index]
GO

ALTER TABLE [dbo].[Dim_TJFF] ADD CONSTRAINT PK_Dim_TJFF_Id PRIMARY KEY([TJFFId])
GO
