CREATE DATABASE BI_ODS
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'BI_ODS', FILENAME = N'D:\BIDatabases\BI_ODS.mdf' , SIZE = 5120KB , FILEGROWTH = 524288KB )
 LOG ON 
( NAME = N'BI_ODS_log', FILENAME = N'D:\BIDatabases\BI_ODS_log.ldf' , SIZE = 1024KB , FILEGROWTH = 524288KB )
GO
GO

/*
索引文件
*/
IF (EXISTS(SELECT 1 FROM [sys].[sysfiles] AS sf WITH(NOLOCK) WHERE [sf].[name] = 'PF_PRIMARY_Index01'))
BEGIN
	DBCC SHRINKFILE([PF_PRIMARY_Index01], EMPTYFILE);
	ALTER DATABASE [BI_ODS] REMOVE FILE [PF_PRIMARY_Index01];
END
GO
IF (EXISTS(SELECT 1 FROM [sys].[sysfiles] AS sf WITH(NOLOCK) WHERE [sf].[name] = 'PF_PRIMARY_Index02'))
BEGIN
	DBCC SHRINKFILE([PF_PRIMARY_Index02], EMPTYFILE);
	ALTER DATABASE [BI_ODS] REMOVE FILE [PF_PRIMARY_Index02];
END
GO
IF (EXISTS(SELECT 1 FROM [sys].[sysfiles] AS sf WITH(NOLOCK) WHERE [sf].[name] = 'PF_PRIMARY_Index03'))
BEGIN
	DBCC SHRINKFILE([PF_PRIMARY_Index03], EMPTYFILE);
	ALTER DATABASE [BI_ODS] REMOVE FILE [PF_PRIMARY_Index03];
END
GO
IF (EXISTS(SELECT 1 FROM [sys].[sysfiles] AS sf WITH(NOLOCK) WHERE [sf].[name] = 'PF_PRIMARY_Index04'))
BEGIN
	DBCC SHRINKFILE([PF_PRIMARY_Index04], EMPTYFILE);
	ALTER DATABASE [BI_ODS] REMOVE FILE [PF_PRIMARY_Index04];
END
GO
IF (EXISTS(SELECT 1 FROM [sys].[sysfiles] AS sf WITH(NOLOCK) WHERE [sf].[name] = 'PF_PRIMARY_Index05'))
BEGIN
	DBCC SHRINKFILE([PF_PRIMARY_Index05], EMPTYFILE);
	ALTER DATABASE [BI_ODS] REMOVE FILE [PF_PRIMARY_Index05];
END
GO

/*
索引文件组
*/
IF (EXISTS(SELECT 1 FROM [sys].[filegroups] AS fg WITH(NOLOCK) WHERE [fg].[name] = 'FG_PRIMARY_Index'))
BEGIN
	ALTER DATABASE [BI_ODS] REMOVE FILEGROUP [FG_PRIMARY_Index]
END
GO


/*
索引文件组
*/
ALTER DATABASE [BI_ODS] ADD
FILEGROUP [FG_PRIMARY_Index]
GO


/*
创建索引文件
*/
ALTER DATABASE [BI_ODS] ADD
FILE (
	NAME = 'PF_PRIMARY_Index01',
	FILENAME = 'D:\BIDatabases\PRIMARY_Indexs_ODS\PF_PRIMARY_Index01.NDF',
	SIZE = 2048MB,
	FILEGROWTH = 512MB
) TO FILEGROUP [FG_PRIMARY_Index]

ALTER DATABASE [BI_ODS] ADD
FILE (
	NAME = 'PF_PRIMARY_Index02',
	FILENAME = 'D:\BIDatabases\PRIMARY_Indexs_ODS\PF_PRIMARY_Index02.NDF',
	SIZE = 2048MB,
	FILEGROWTH = 512MB
) TO FILEGROUP [FG_PRIMARY_Index]

ALTER DATABASE [BI_ODS] ADD
FILE (
	NAME = 'PF_PRIMARY_Index03',
	FILENAME = 'D:\BIDatabases\PRIMARY_Indexs_ODS\PF_PRIMARY_Index03.NDF',
	SIZE = 2048MB,
	FILEGROWTH = 512MB
) TO FILEGROUP [FG_PRIMARY_Index]

ALTER DATABASE [BI_ODS] ADD
FILE (
	NAME = 'PF_PRIMARY_Index04',
	FILENAME = 'D:\BIDatabases\PRIMARY_Indexs_ODS\PF_PRIMARY_Index04.NDF',
	SIZE = 2048MB,
	FILEGROWTH = 512MB
) TO FILEGROUP [FG_PRIMARY_Index]

ALTER DATABASE [BI_ODS] ADD
FILE (
	NAME = 'PF_PRIMARY_Index05',
	FILENAME = 'D:\BIDatabases\PRIMARY_Indexs_ODS\PF_PRIMARY_Index05.NDF',
	SIZE = 2048MB,
	FILEGROWTH = 512MB
) TO FILEGROUP [FG_PRIMARY_Index];
GO